name: challenge2

on: push

env:
    FILE_NAME: hello-server.txt
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v1
        - name: Upload artifact for linux
          uses: actions/upload-artifact@v1.0.0
          with:
            name: linux
            path: ./${{ env.FILE_NAME }}