name: challenge2

on: push

env:
    FILE_NAME: hello-server
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              use: actions/checkout@v1
            - name: Upload artifact for linux
              use: actions/upload-artifact@v1.0.0
              with:
                name: ${{ env.FILE_NAME }}
                path: .